name: Unit_tests

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v3
    - name: Step 2 - Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Step 3 - Run Unit Tests
      run: mvn -ntp -Dskip.installnodenpm -Dskip.npm verify --batch-mode -Dlogging.level.ROOT=OFF -Dlogging.level.org.zalando=OFF -Dlogging.level.tech.jhipster=OFF -Dlogging.level.sn.trivial.ticket=OFF -Dlogging.level.org.springframework=OFF -Dlogging.level.org.springframework.web=OFF -Dlogging.level.org.springframework.security=OFF

  curl:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X POST "http://207.180.198.161:8080" -d 'from lamine'
        
