name: Unit_tests

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v3
    - name: Step 2 - Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Step 3 - Run Unit Tests
      run: mvn -ntp -Dskip.installnodenpm -Dskip.npm verify --batch-mode -Dlogging.level.ROOT=OFF -Dlogging.level.org.zalando=OFF -Dlogging.level.tech.jhipster=OFF -Dlogging.level.sn.trivial.ticket=OFF -Dlogging.level.org.springframework=OFF -Dlogging.level.org.springframework.web=OFF -Dlogging.level.org.springframework.security=OFF

  curl:
    runs-on: ubuntu-latest
    needs: test
    environment: jenkins_env
    steps:
    - name: curl
      uses: indiesdev/curl@v1.1
      env:
        jenkins_server_ip: ${{ secrets.JENKINS_SERVER_IP }}
        authentication_token: ${{ secrets.AUTHENTICATION_TOKEN }}
        jenkins_server_auth: ${{ secrets.JENKINS_SERVER_AUTH }}
      with:
          url: "http://$jenkins_server_ip/job/tickets_management_building_image/build"
          method: "GET"
          accept: 200,201,204
          headers: '{ "Authorization": "Basic $jenkins_server_auth" }'
          params: '{ "token": "$authentication_token"}'
          timeout: 1000
          #basic-auth-token: "$jenkins_server_auth"
          log-response: false
          retries: 3        
